language: csharp
solution: /CalculatorProject/CalculatorProject.sln

script:
- xbuild /p:Configuration=Release /CalculatorProject/CalculatorProject.sln
- mono ./CalculatorProject/Calculator.Test.Unit/bin/Debug/Calculator.Test.Unit.dll